### ISSUE TITLE
Code seems to fail near the poles.

### ISSUE THREAD

**Issue by cyga74** [npbassett/shapes#1]
Example.  Trying to run the code at 88 degrees south, zero degrees latitude results in the following.

(0, -88)
Read lunar elevation data in 0.08 minutes
Traceback (most recent call last):
  File "C:\Users\nordme1\shapes\shapes\BaseHorizonCalculator.py", line 250, in horizon_profile
    import progressbar
ModuleNotFoundError: No module named 'progressbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nordme1\shapes\examples\lunar_horizon_calculator.py", line 20, in <module>
    lunar_horizon_calculator.horizon_profile(N_alpha, N_gamma)
  File "C:\Users\nordme1\shapes\shapes\BaseHorizonCalculator.py", line 263, in horizon_profile
    horizon_angles += [self.horizon_angle(azimuths[i], gamma)]
  File "C:\Users\nordme1\shapes\shapes\BaseHorizonCalculator.py", line 228, in horizon_angle
    h = self.interpolate_elevation(alpha, gamma)
  File "C:\Users\nordme1\shapes\shapes\BaseHorizonCalculator.py", line 213, in interpolate_elevation
    return self.elevation_interpolation_function(l, b, grid=False)
  File "C:\Users\nordme1\shapes\shapes\BaseHorizonCalculator.py", line 170, in elevation_interpolation_function
    self._elevation_interpolation_function = RectBivariateSpline(\
  File "C:\Users\nordme1\AppData\Local\Continuum\anaconda3\envs\testgdalnord1\lib\site-packages\scipy\interpolate\fitpack2.py", line 1336, in __init__
    raise ValueError('y dimension of z must have same number of '
ValueError: y dimension of z must have same number of elements as y

**Comment by npbassett** [comment]
Thanks for bringing this to my attention! Not sure exactly how to fix this problem at the moment, but I'll work on it!

**Comment by cyga74** [comment]
Thanks!

I'm interested in doing some illumination studies near the poles.

Found out about your codebase at a talk you gave a few weeks ago.

**Comment by npbassett** [comment]
The newest commits should solve this problem (at least for the Moon)! For Earth-based locations, there's still an issue because the [elevation python package](https://pypi.org/project/elevation/) that I use to get the elevation data can only pull so many tiles from the host site for some reason. A fix would probably involve getting elevation data from another source, but I don't think it's as important so I'm not going to worry about it for now.
